num = 2
f = 2.5
print(type(num))
print(type(f))
num2 = str(num)
print(num2)
print(type(num2))
f2 = str(f)
print(f)
print(type(f))
str1 = "5"
print(type(str1))
int1 = int(str1)
print(int1)
print(type(int1))
f3 = float(str1)
print(type(f3))
num1 = 2
print(num1)
print(type(num1))
f = float(num1)
print(type(f))
print(f)
f1 = int(f)
print(f1)
print(type(f1))
tup1 = (1,2,3)
print(type(tup1))
list1 = list(tup1)
print(type(list1))
print(list1)
tup = tuple(list1)
print(tup)
print(list1)
set1 = set(list1)
print(type(set1))


num = 10
num_bin = bin(num)
print(num_bin)
num_hex = hex(num)
print(num_hex)
bin_to_num = int(num_bin, 2)
print(bin_to_num)
hex_to_num = int(num_hex, 16)
print(hex_to_num)