my_tuple = ()
print(type(my_tuple))
my_tuple = (9)
print(type(my_tuple))
my_tuple = (9,)
print(type(my_tuple))
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple)
print(my_tuple[0])
print(my_tuple[1])
print(my_tuple[-1])
print("10:30")
print("2Hours")
print("12:17")
print("12:30")
print("2Hours")
print("3:40")

tuple1 = ("Cisco", "2600", "12.4")

(vendor, model, ios) = tuple1
print(vendor)
print(model)
print(ios)