print(1 == 1)
print(1 == 2)
print("python" == "python")
print("python" == "Python")
print(3 <= 4)
print((1 == 1) and (2 == 2))
print((1 == 2) and (3 == 2))
print((1 == 1) and (3 == 2))
print((1 == 1) or (2 == 2))
print((1 == 1) or (2 == 3))
print((1 == 2) or (2 == 3))
print(not(1 == 1))
print(not(1 == 2))
print(1 ,bool())
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(1))
print(bool(2.2))
print(bool([]))
print(bool({}))