creeper_BOOM_range = range(10)
print(creeper_BOOM_range)
print(type(creeper_BOOM_range))
print(list(creeper_BOOM_range))
print(creeper_BOOM_range[0])
print(creeper_BOOM_range[-1])
print(10 in creeper_BOOM_range)
print(7 not in creeper_BOOM_range)
print(7 in creeper_BOOM_range)
print(creeper_BOOM_range.index(4))
print(list(creeper_BOOM_range)[2:5])
