tuple2 = (1, 2, 3, 4)
print(len(tuple2))
print(min(tuple2))
print(max(tuple2))
print(tuple2)
print(tuple2 + (5, 6, 7))
print(tuple2 * 2)
print(tuple2[0:2])
print(tuple2[:2])
print(tuple2[1:])
print(tuple2[:])
print(tuple2[:-2])
print(tuple2[-2:])
print(tuple2[::-1])
print(tuple2)
print(3 in tuple2)
print(3 not in tuple2)
print(5 in tuple2)
del tuple2
#print(tuple2)
#Will give error if you unhasteg "print(tuple2)"