susple = (1, 2, 3, 4)
print(len(susple))
print(min(susple))
print(max(susple))
print(susple)
print(susple + (5, 6, 7))
print(susple * 2)
print(susple[0:2])
print(susple[2:4])
print(susple[-2])
print(susple[:-2])
print(susple[:-3])
print(susple[-2:])
print(susple[-3:])
print(susple[::-1])
print(susple[::2])
print(susple)
print(3 in susple)
print(3 not in susple)
print(5 in susple)
print(5 not in susple)
del susple
# print(susple)
