newworld = open("E:\ORAORAORA.txt", "w")
newworld.write(
    "ORA YARE YARE DAZE STAR PLATINUM\nORA ORA ORA ORA ORA ORA ORA ORA\nORA ORA ORA ORA ORA ORA ORA ORA\nORA ORA ORA ORA ORA ORA ORA ORA\nORA ORA ORA ORA ORA ORA ORA ORA")

newworld.close()
